### ISSUE TITLE
Error when using itch-dl

### ISSUE THREAD

**Issue by proximitysound** [DragoonAethis/itch-dl#20]
I'm getting this error when trying to run itch-dl for a recent Jam 

```
Traceback (most recent call last):
  File "/usr/local/bin/itch-dl", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/itch_dl/cli.py", line 81, in run
    return drive_downloads(jobs, download_to, args.mirror_web, settings, keys, parallel=args.parallel)
  File "/usr/local/lib/python3.9/site-packages/itch_dl/downloader.py", line 353, in drive_downloads
    results = [downloader.download(job) for job in tqdm(jobs, **tqdm_args)]
  File "/usr/local/lib/python3.9/site-packages/itch_dl/downloader.py", line 353, in <listcomp>
    results = [downloader.download(job) for job in tqdm(jobs, **tqdm_args)]
  File "/usr/local/lib/python3.9/site-packages/itch_dl/downloader.py", line 240, in download
    metadata = self.extract_metadata(game_id, url, site)
  File "/usr/local/lib/python3.9/site-packages/itch_dl/downloader.py", line 150, in extract_metadata
    infobox = parse_infobox(infobox_div)
  File "/usr/local/lib/python3.9/site-packages/itch_dl/infobox.py", line 121, in parse_infobox
    parsed_block = parse_tr(name, content_td)
  File "/usr/local/lib/python3.9/site-packages/itch_dl/infobox.py", line 58, in parse_tr
    return "published_at", parse_date_block(content)
  File "/usr/local/lib/python3.9/site-packages/itch_dl/infobox.py", line 38, in parse_date_block
    time = datetime.strptime(time_str.strip(), "%H:%M")
  File "/usr/local/Cellar/python@3.9/3.9.19_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/Cellar/python@3.9/3.9.19_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains:  UTC
```
The Jam in question is https://itch.io/jam/gbpixelartjam24

**Comment by proximitysound** [comment]
Nevermind, uninstalled and reinstalled to solve.
